export default {
  LOAD_COURSES: "LOAD_COURSES",
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  LOAD_AUTHORS: "LOAD_AUTHORS",
  CREATE_AUTHORS: "CREATE_AUTHORS",
  UPDATE_AUTHORS: "UPDATE_AUTHORS",
  DELETE_AUTHORS: "DELETE_AUTHORS"
};
